name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Railway CLI
      run: npm i -g @railway/cli
      
    - name: Deploy to Railway
      env:
        # Required: Railway deployment token
        # Get this from Railway Dashboard > Project Settings > Service > Tokens
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service elion-twitter-bot
