name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      env:
        # These secrets must be configured in your GitHub repository settings
        # Go to Settings > Secrets and variables > Actions > New repository secret
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}         # Required: Twitter API Key
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}   # Required: Twitter API Secret
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }} # Required: Twitter Access Token
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }} # Required: Twitter Access Secret
        CRYPTORANK_API_KEY: ${{ secrets.CRYPTORANK_API_KEY }}   # Required: CryptoRank API Key
        CRYPTORANK_BASE_URL: https://api.cryptorank.io/v2
        LLM_MODEL: meta/llama-2-70b-chat
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}                # Required: LLM API Key
        ENVIRONMENT: test
      run: |
        python -m pytest tests/ -v
